### ISSUE TITLE
Show modal on the top of the parent view

### ISSUE THREAD

**Issue by vishwas247** [react-native-modal/react-native-modal#409] opened 2020-03-05 05:27 UTC
## Ask your Question

Hi, I  am using  this modal inside a screen which is embed in a tab-bar-bottom component which is always visible on bottom to switch the screen. So I want to show modal by covering the bottom tab bar when presents from bottom. Currently it is presenting from behind. Is there any way or property I can achieve this?

**Comment by acatalina** [comment] 2020-04-01 18:30
is it an option to hide the tab bar when the modal comes up?

**Comment by mmazzarolo** [comment] 2021-08-29 13:25
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:25 UTC
Labels: question, stackoverflow
