### ISSUE TITLE
AnimationOut is not working when conditional state is setted

### ISSUE THREAD

**Issue by Bayramito** [react-native-modal/react-native-modal#455] opened 2020-07-03 09:15 UTC
Hi,

I dunno is that a bug but, if i call components  depends a condition, dissappearing animations are not working.  

I mean, lets say i have 2 components componentA and componentB, and in the modal as a children if i call these 2 components depends on a condition like if ... ... then call componentA else call componentA, animation is not working.

here is my code:
`<Modal
	style={{
		flexDirection: "column",
		justifyContent: "center",
		alignItems: "center",
		flex: 1,
	}}
	hasBackdrop={true}
	useNativeDriver
	animationIn="tada"
	animationOut="wobble"
	animationOutTiming={1000}
	deviceWidth={width}
	deviceHeight={height}
	width={width}
	backdropColor="rgba(0,0,0,.5)"
	avoidKeyboard={true}
	isVisible={isVisible}
	onBackdropPress={() => {}}
>
	<>
		<View style={styles.container}>
			{alert.type == "dialog" ? (
				<View style={styles.wrapper}>
					<View style={styles.header}>
						<Text style={[textStyles.boldSemi, textStyles.fontSize20]}>
							{alert.title}
						</Text>
						<TouchableOpacity onPress={() => app.CloseAlert()}>
							<FastImage
								source={imagesEvent.close}
								style={{ width: 30, height: 30 }}
								resizeMode={FastImage.resizeMode.contain}
							/>
						</TouchableOpacity>
					</View>
					<View style={styles.content}>
						<Text style={[textStyles.light, textStyles.fontSize16]}>
							{alert.message}
						</Text>
					</View>
					<View style={styles.buttons}>
						<TouchableOpacity
							style={styles.button}
							onPress={() => this.handleCancel()}
						>
							<Text
								style={[
									styles.btn_text,
									textStyles.bold,
									textStyles.fontSize16,
									{
										backgroundColor: colorsComponent.backgroundColorSoft,
									},
								]}
							>
								{cancelText ? cancelText : "Hayır"}
							</Text>
						</TouchableOpacity>
						<TouchableOpacity
							style={styles.button}
							onPress={() => this.handleAccept()}
						>
							<Text
								style={[
									styles.btn_text,
									textStyles.bold,
									textStyles.fontSize16,
									{
										backgroundColor: colorsComponent.mainBackgroundColor,
									},
								]}
							>
								{acceptText ? acceptText : "Evet"}
							</Text>
						</TouchableOpacity>
					</View>
				</View>
			) : alert.type == "warning" ? (
				<View style={styles.wrapper}>
					<View
						style={{
							flexDirection: "column",
							justifyContent: "center",
							alignItems: "center",
						}}
					>
						<FastImage
							source={imagesPost.warning}
							style={{ width: 30, height: 30 }}
							resizeMode={FastImage.resizeMode.contain}
						/>
						<Text
							style={[textStyles.boldSemi, textStyles.fontSize20, {}]}
						>
							{alert.title}
						</Text>
					</View>
					<View style={styles.content}>
						<Text style={[textStyles.light, textStyles.fontSize16]}>
							{alert.message}
						</Text>
					</View>
					<View style={[styles.buttons]}>
						<TouchableOpacity
							style={{}}
							onPress={() => this.handleAccept()}
						>
							<Text
								style={[
									styles.btn_text,
									textStyles.bold,
									textStyles.fontSize16,
									{
										backgroundColor: colorsComponent.mainBackgroundColor,
									},
								]}
							>
								{acceptText ? acceptText : "Evet"}
							</Text>
						</TouchableOpacity>
					</View>
				</View>
			) : null}
		</View>
	</>
</Modal>`

**Comment by alexzobi** [comment] 2020-07-09 17:50
If I understand the OP, I'm experiencing the same problem. No out animation, even if i try to hardcode. `animationIn` works as expected out of the box. 

```
<Modal
  isVisible={this.state.isActive}
  onBackdropPress={() => this.setState({ isActive: false })}
  onModalHide={() => this.setState({ isActive: false })}
  backdropOpacity={0.25}
>
  <Text>This is a test</Text>
</Modal>
```

resulting code has `animationIn` of slideInUp with a fading in backdrop, but `onBackdropPress` and `onModalHide` both result in immediate disappearance of modal and backdrop, no transitions.

**Comment by MattGoldwater** [comment] 2020-10-28 20:01
I can't get animationOut to work at all.

**Comment by mmazzarolo** [comment] 2021-08-29 13:16
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:16 UTC
Labels: bug
