### ISSUE TITLE
override  Modal props

### ISSUE THREAD

**Issue by eran88** [react-native-modal/react-native-modal#529] opened 2021-03-21 10:58 UTC
## Ask your Question

Can you add a method to override modal props?
For example, I want to use onRequestClose prop in order to close the modal when the user using the android back button.

**Comment by mmazzarolo** [comment] 2021-08-29 13:06
Hi! 
I'm closing this issue because it's a question and not a bug report.    
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:06 UTC
Labels: question
