### ISSUE TITLE
ref.current.open() doesn't work

### ISSUE THREAD

**Issue by borasumer** [react-native-modal/react-native-modal#578] opened 2021-07-22 16:24 UTC
## Ask your Question

I am trying to save the modalRef in a context and trigger the modal from other components using modalRef.current.open() or close(), even though ref functions are there when I console log the modalRef, they don't seem to be working for some reason. Not sure what I am doing wrong or it is a bug.
This is my code for the modal:

```
  const modalRef = useRef(null);

  <Modal
        ref={modalRef}
        backdropColor="#344356"
        animationIn="zoomInUp"

        style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}
        backdropTransitionOutTiming={0}
        hideModalContentWhileAnimating
        statusBarTranslucent
      >
        <ModalView>Some buttons and text...</ModalView>
      </Modal>
```
Thanks

**Comment by NathanBeesley** [comment] 2021-07-22 20:14
Im not sure this will work. isVisible prop is required which dictates when the Modal will be visible. You could use context to set the visible state.

**Comment by mmazzarolo** [comment] 2021-08-29 13:13
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:13 UTC
Labels: question
