### ISSUE TITLE
Modal Disappearing when custom Notification is closed

### ISSUE THREAD

**Issue by rahulje9** [react-native-modal/react-native-modal#429] opened 2020-04-29 05:35 UTC
Hi,

I have an app with a modal having the UI as shown as in the image. 
The blue notification bar is a custom notification bar which pops up on the launch of the modal. I want to close the notification bar only when the close icon is pressed in the notification bar. 
In ios it is working as expected, but with other issues. after close the blue notification bar I'm not able to close the modal on backdrop press. it's hit or miss at times. In android I'm not able to close the notification bar, It just closes the modal Instead.

I have the latest version of `react-native-modal`

![Screenshot 2020-04-29 at 10 52 49 AM](https://user-images.githubusercontent.com/22475675/80563402-b0df0a00-8a08-11ea-8e28-1228a49115cd.png)

**Comment by mmazzarolo** [comment] 2021-08-29 13:23
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:23 UTC
Labels: bug
