### ISSUE TITLE
how to set modal like this?

### ISSUE THREAD

**Issue by liuqing520it** [react-native-modal/react-native-modal#595] opened 2021-08-24 07:47 UTC
## Ask your Question

![1233](https://user-images.githubusercontent.com/16216435/130577679-bb33b082-74f4-4ba1-bf26-a44e5071be12.png)

**Comment by mmazzarolo** [comment] 2021-08-29 13:05
Hi! 
I'm closing this issue because it's a question and not a bug report.    
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:05 UTC
Labels: question
