### ISSUE TITLE
OnSwipeStart and other Swipe related properties works on Elements inside Modal, not on Transparent part

### ISSUE THREAD

**Issue by atspatel** [react-native-modal/react-native-modal#435] opened 2020-05-25 07:52 UTC
## Ask your Question
I render transparent modal, with few list items on flex-start (at top). items covers almost half screen, remaining half is transparent. OnSwipeStart only works in when I start swipe on Items (Upper half), but it doesn't work on bottom half. 
I want to close the modal on swipe up anywhere on screen. 
<img width="450" alt="Screenshot 2020-05-25 at 1 23 44 PM" src="https://user-images.githubusercontent.com/12714408/82791212-fa493a80-9e8a-11ea-9e57-f6272273e9c5.png">

**Comment by mmazzarolo** [comment] 2021-08-29 13:22
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:22 UTC
Labels: question
