### ISSUE TITLE
Swipe options

### ISSUE THREAD

**Issue by rogic89** [react-native-modal/react-native-modal#437] opened 2020-05-27 15:36 UTC
Hi, I am trying to build something similar to iPhone maps app. The swippable modal opening when you click on map elements.

My question is:
- If I start swiping down, I can't swipe up in the same motion (without release) anymore and vice versa. Any way around that?
- On `onSwipeMove` I don't get a direction of the swipe along with percentage. This would be really useful and should be implemented.

Love the lib! :)

**Comment by raffibag** [comment] 2021-04-18 16:45
+1 on getting the swiping direction `onSwipeMove`. Or make the percentage read negative based on direction?

**Comment by mmazzarolo** [comment] 2021-08-29 13:22
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:22 UTC
Labels: question
