### ISSUE TITLE
Disable modal animationIn and animationOut

### ISSUE THREAD

**Issue by vikjovanov** [react-native-modal/react-native-modal#471] opened 2020-08-10 14:02 UTC
Hi, 

I have a very small and simple question: How can I remove animations from my modal?

I wish I could have a modal that opens and closes without animation, is that possible?

Thanks

**Comment by akk7300** [comment] 2020-08-14 18:10
@vikjovanov 

Set animationInTiming and animationOutTiming to 1.
example

`<Modal 
               animationInTiming={1}
              animationOutTiming={1}
</Modal>
`

**Comment by anhquan291** [comment] 2020-11-20 09:30
> @vikjovanov
> 
> Set animationInTiming and animationOutTiming to 1.
> example
> 
> `<Modal animationInTiming={1} animationOutTiming={1} > </Modal> `

Thank you but it doesn't work for me :(

**Comment by mmazzarolo** [comment] 2021-08-29 13:12
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:12 UTC
Labels: question
