### ISSUE TITLE
open modal by swiping up?

### ISSUE THREAD

**Issue by picknamexd** [react-native-modal/react-native-modal#575] opened 2021-07-16 20:30 UTC
Is there any way to open the modal by swiping up like opening gallery from camera on instagram or whatsap?

**Comment by mmazzarolo** [comment] 2021-08-29 13:05
Hi! 
I'm closing this issue because it's a question and not a bug report.    
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:05 UTC
Labels: question
