### ISSUE TITLE
[Question] Is it possible to interact with the backdrop?

### ISSUE THREAD

**Issue by sauhardar** [react-native-modal/react-native-modal#444] opened 2020-06-05 23:16 UTC
I want to make it so that the Modal is used similar to an absolutely positioned `View` component. I want to use the modal mostly for its animation features since I'm using the package in other places anyway. Is it possible to have it there and interact with the background (ie what would have been the backdrop)? Don't see a prop enabling this.

**Comment by mmazzarolo** [comment] 2021-08-29 13:21
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:21 UTC
Labels: question
