### ISSUE TITLE
setModalVisible not working/

### ISSUE THREAD

**Issue by aphrim** [react-native-modal/react-native-modal#522] opened 2021-02-18 22:25 UTC
I Have been trying to make a toggleable Modal. I practically copy pasted this code from the Read_Me, but it doesn't seem to work. I have the modal visible by default and have it on an onBackDropPress it calls this function. `const [isModalVisible, setModalVisible] = useState(false);` `    const toggleModal = () => {
      setModalVisible(!isModalVisible);
      console.log('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
    };`. It prints the 'aaaaaaaaaaaaaaaaa' but doesn't actually hide the Modal. I also tried just doing false instead of !isModalVisible. Any help would be greatly appreciated!

**Comment by ragranados** [comment] 2021-03-08 21:25
the problem its only on iOS or android too? im haveing that problem on iOS only :/

**Comment by EricWiener** [comment] 2021-05-13 03:20
I'm also having this problem. Have either of you found any work-around?

**Comment by hmarques98** [comment] 2021-05-14 22:17
https://github.com/react-native-modal/react-native-modal/issues/534#issuecomment-841331077

I commented about my found solution for this bug.

It's because IOS not allow two modals in same time

**Comment by EricWiener** [comment] 2021-05-15 14:00
@hmarques98 this is not the same bug

**Comment by mmazzarolo** [comment] 2021-08-29 13:13
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:13 UTC
Labels: question
