### ISSUE TITLE
Android - Modal background color is not set

### ISSUE THREAD

**Issue by adimallikarjunareddy** [react-native-modal/react-native-modal#388] opened 2020-01-03 04:41 UTC
## Environment

<pre>
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 189.24 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.0 => 0.61.0
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
</pre>

## Platforms

<pre> Android </pre>

## Versions

- Android: API Version 28
- react-native-modal:9.0.0
- react-native:0.61.0
- react:16.9.0

## Description

The Modal has been working fine till we did bunch of upgrades to RN and the dependent packages.
After the upgrade we started seeing that the Modal dialog background color is lost and is mixed with the transparent background.

**Comment by jclough96** [comment] 2020-02-27 11:33
Any updates on this? We are experiencing this on RN0.61.*

**Comment by littlehome-eugene** [comment] 2020-03-29 13:36
same problem here , although we can just give backgroundColor style.

**Comment by rewieer** [comment] 2020-04-02 05:32
If anyone can submit a repository i'd check it

**Comment by Suresh-R-S** [comment] 2020-08-17 20:31
Noticed it in production build and not in debug mode. Once the modal appears with transparent background all the other modals will have the same behaviour.

**Comment by vigneshr0315** [comment] 2021-03-05 10:21
Any updates on this?

**Comment by Nirodha26** [comment] 2021-06-09 13:26
I'm experiencing same issue for react-native 0.61 and react-native-modal 11.6.1

Any update on this issue?

**Comment by vigneshr0315** [comment] 2021-06-09 13:44
@Nirodha26 Try wrapping it inside SafeAreaView from react-navigation

`<SafeAreaView forceInset={{ top: 'never', bottom: 'never' }} style={getContainerStyle()}>
                        {
                        // content goes here
                        }
                    </SafeAreaView>`

**Comment by mmazzarolo** [comment] 2021-08-29 13:26
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:26 UTC
Labels: bug, missing reproducible
