### ISSUE TITLE
Previous component visible, when keyboard opens on Modal, Only in Android

### ISSUE THREAD

**Issue by TaraSinghDanu** [react-native-modal/react-native-modal#430] opened 2020-05-05 14:59 UTC
```
<View>
      <Modal
        isVisible={showModal}
        style={{
          justifyContent: 'flex-end',
          margin: 0,
        }}>
        <View style={style.container}>
          <HeaderUserType
            title='Header'
            showBackButton
            showCrossButton={false}
            onBackButtonPress={handleBackButtonPress}
          />
          <KeyboardAwareScrollView
            contentContainerStyle={{ alignItems: 'center', flexGrow: 1 }} showsVerticalScrollIndicator={false}>
            <Text
              style={[
                style.validationTitleText,
                { marginTop: heightScale(30) },
              ]}>
              {''}
            </Text>
            <Text
              style={[
                style.validationTitleText,
                {
                  fontFamily: fontFamily.verdanaBold,
                  marginTop: heightScale(10),
                },
              ]}>
              {strings.PLEASE_PROVIDE_THE_FOLLOWING_INFORMATION}
            </Text>
            <TextField
              onFocus={() => setIdFocused(true)}
              onBlur={() => setlIdFocused(false)}
              containerStyle={{ marginTop: heightScale(50) }}
              placeholderLabel={strings.ID}
              label={strings.ID}
              showLabel={IdFocused || Id.length > 0}
              onChangeText={setId}
              value={Id}
            />
            <TextField
              onFocus={() => setNameFocused(true)}
              onBlur={() => setNameFocused(false)}
              containerStyle={{ marginTop: heightScale(20) }}
              placeholderLabel={strings.YOUR_FULL_NAME}
              label={strings.YOUR_FULL_NAME}
              showLabel={nameFocused || name.length > 0}
              onChangeText={setName}
              value={name}
            />
            <View style={[style.bottomButtonsView, { bottom: bottom }]}>
              <Button
                title=''click"
                isDisabled={!enableButton}
                onButtonClick={sendDataToServer}
                customStyle={{ opacity: enableButton ? 1 : 0.5 }}
              />
            </View>
          </KeyboardAwareScrollView>
        </View>
      </Modal>
    </View>
``
<img width="506" alt="Screenshot 2020-05-05 at 8 51 43 PM" src="https://user-images.githubusercontent.com/16621822/81384931-12515800-9130-11ea-97c3-d7c9d85f2824.png">

"react-native-modal": "^11.5.6",
"react": "16.9.0",
"react-native": "0.61.5",

**Comment by shivam05aggarwal** [comment] 2020-05-05 15:03
Getting the error..

**Comment by TaraSinghDanu** [comment] 2020-05-05 15:26
> ```
> <View>
>       <Modal
>         isVisible={showModal}
>         style={{
>           justifyContent: 'flex-end',
>           margin: 0,
>         }}>
>         <View style={style.container}>
>           <HeaderUserType
>             title='Header'
>             showBackButton
>             showCrossButton={false}
>             onBackButtonPress={handleBackButtonPress}
>           />
>           <KeyboardAwareScrollView
>             contentContainerStyle={{ alignItems: 'center', flexGrow: 1 }} showsVerticalScrollIndicator={false}>
>             <Text
>               style={[
>                 style.validationTitleText,
>                 { marginTop: heightScale(30) },
>               ]}>
>               {''}
>             </Text>
>             <Text
>               style={[
>                 style.validationTitleText,
>                 {
>                   fontFamily: fontFamily.verdanaBold,
>                   marginTop: heightScale(10),
>                 },
>               ]}>
>               {strings.PLEASE_PROVIDE_THE_FOLLOWING_INFORMATION}
>             </Text>
>             <TextField
>               onFocus={() => setIdFocused(true)}
>               onBlur={() => setlIdFocused(false)}
>               containerStyle={{ marginTop: heightScale(50) }}
>               placeholderLabel={strings.ID}
>               label={strings.ID}
>               showLabel={IdFocused || Id.length > 0}
>               onChangeText={setId}
>               value={Id}
>             />
>             <TextField
>               onFocus={() => setNameFocused(true)}
>               onBlur={() => setNameFocused(false)}
>               containerStyle={{ marginTop: heightScale(20) }}
>               placeholderLabel={strings.YOUR_FULL_NAME}
>               label={strings.YOUR_FULL_NAME}
>               showLabel={nameFocused || name.length > 0}
>               onChangeText={setName}
>               value={name}
>             />
>             <View style={[style.bottomButtonsView, { bottom: bottom }]}>
>               <Button
>                 title=''click"
>                 isDisabled={!enableButton}
>                 onButtonClick={sendDataToServer}
>                 customStyle={{ opacity: enableButton ? 1 : 0.5 }}
>               />
>             </View>
>           </KeyboardAwareScrollView>
>         </View>
>       </Modal>
>     </View>
> ``
> <img width="492" alt="Screenshot 2020-05-05 at 8 53 33 PM" src="https://user-images.githubusercontent.com/16621822/81083879-c37aa700-8f12-11ea-86c8-0fcf8d8b8f27.png">
> ```

"react-native-modal": "^11.5.4",
 "react": "16.9.0",
"react-native": "0.61.5",

**Comment by TaraSinghDanu** [comment] 2020-05-23 14:36
Anyone else facing the same issue?

**Comment by 15110011** [comment] 2020-05-29 08:11
in my case is previous component still appear there 1s or 2s then disappear when I press close modal

**Comment by mmazzarolo** [comment] 2021-08-29 13:23
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:23 UTC
Labels: question

**Comment by nes123** [comment] 2024-11-16 16:55
it is a bug..the parent view can be seen when the keyboard open or close in a modal
