### ISSUE TITLE
Rendering case sensetive  components in a single modal

### ISSUE THREAD

**Issue by Bayramito** [react-native-modal/react-native-modal#510] opened 2021-01-07 10:56 UTC
Is it possible to use this modal to render case sensetive  components inside it?

I mean in a screen I have 2 or 3 modal types depends on buttons. For example modal for sorting, modal for reaction modal for options etc...
`
   <Modal
	style={{
			marginLeft: 0,
			flexDirection: "column",
			justifyContent: "flex-end",
			marginBottom: 0,
		}}
		onBackButtonPress={() => close()}
		onBackdropPress={() => close()}
		useNativeDriver={true}
		deviceHeight={height}
		deviceWidth={width}
		animationInTiming={500}
		animationOutTiming={700}
		backdropTransitionInTiming={800}
		backdropTransitionOutTiming={800}
		isVisible={news.modalState.modal}
		children={
			<View style={styles().modalContainer}>
				<Separator width={100} height={3} />

				{type === "options" && <Options />}
				{type === "reaction" && <Reaction />}
				{type === "filter" && <Filter />}
			</View>
		}
			/>`

but if i do like this, when I close the modal it closes immediately. without animation.

any solution for this?

**Comment by mmazzarolo** [comment] 2021-08-29 13:10
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:10 UTC
Labels: question
