### ISSUE TITLE
how to add component in the overlay area 

### ISSUE THREAD

**Issue by FatmaMahmoud698** [react-native-modal/react-native-modal#569] opened 2021-06-20 05:15 UTC
how to make component with zIndex in the transparent area

**Comment by mmazzarolo** [comment] 2021-08-29 13:13
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:13 UTC
Labels: question
