### ISSUE TITLE
Modal on RTL layout

### ISSUE THREAD

**Issue by Filetes97** [react-native-modal/react-native-modal#443] opened 2020-06-03 09:54 UTC
## Ask your Question
Hi guys.

Im having some troubles to make the modal appear in RTL mode in React Native.

Has anyone ever managed to make it work in there? 

Is there any "trick" I'm missing?

**Comment by mmazzarolo** [comment] 2021-08-29 13:21
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:21 UTC
Labels: question
