### ISSUE TITLE
Half of modal always visible on specific app screen

### ISSUE THREAD

**Issue by hvma411** [react-native-modal/react-native-modal#572] opened 2021-06-24 20:11 UTC
Hi, I'm creating my first React Native app and I want to create modal in one of a few app screens but I don't know if it is even possible. 

Example:
Let's say my screen (container for modal) is 100% height of device screen and it contains opened `<Modal> `component like below:

```
<Container>
  <Modal/>
</Container>
```
`<Container>` component has only some photo background.
`<Modal>` component is visible from start, it height is 50% and it has styles: `position: absolute`, `bottom: 0` and it has backdrop turned off.

Now I want to swipe up modal, to make it 80% height of container and then I want to turn on backdrop. I also want to be able to do it backwards - swipe it down to make it 50% height again and then turn backdrop off.

I hope it is good example and anybody will understand it. Is this even possible with this package?

**Comment by pratius** [comment] 2021-06-27 07:59
I'm also facing the same issues. Model is always open on navigation. Is there any fix?

**Comment by sauzy34** [comment] 2021-08-19 17:58
To the `style` property, I added the `marginBottom: -(Number)`. Remember to keep the value as a `negative` number to modify the modal at **(-)Y** axis.

**Comment by mmazzarolo** [comment] 2021-08-29 13:13
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:13 UTC
Labels: question

**Comment by Jamal-ReachFirst** [comment] 2023-01-03 11:50
> n navigation. Is there any fix?

Use `reanimated-bottom-sheet` for this behaviour
