### ISSUE TITLE
Is it possible to render a screen instead of view inside modal?

### ISSUE THREAD

**Issue by Vasault** [react-native-modal/react-native-modal#432] opened 2020-05-14 16:28 UTC
I know this sounds kinda dumb, but my designer asked me to put a quite complex view i already got done in a different screen, inside a modal, so my idea is, instead of setting everything inside the modal with view components and stuff, is it possible to render the whole screen inside the modal?

**Comment by TamerlanG** [comment] 2020-05-19 11:41
why don't you simply use modals from react-navigation ?

**Comment by Vasault** [comment] 2020-05-19 15:41
> why don't you simply use modals from react-navigation ?

i'll check that up, cause i never heard of modals coming from react-navigation

**Comment by Vasault** [comment] 2020-05-19 16:03
i just realize react navigation modal is just an animation that mimics the way modal works, but is not a proper modal, i just want to cover the 80% of the screen, so that way the user knows that you're opening a modal

**Comment by Jmzp** [comment] 2020-05-20 21:09
@Vasault It is possible to simulate this behaviour, you can add margins to the sides and make the content occupy 100% of the screen.

This library is very dynamic, I created a toast using this library since it offers gestures that I don't need to reprogram.

**Comment by Vasault** [comment] 2020-05-20 21:13
what i meant to say, is that i need the screen to be mounted on top the other, but the idea is that the parts you mention to put some margins, should be transparent, so that you can still see the screen below, is that possible?

**Comment by Jmzp** [comment] 2020-05-20 21:26
@Vasault yes, it is possible, like this: 

![image](https://user-images.githubusercontent.com/22944576/82498804-33159800-9ab6-11ea-9305-b30d2320f928.png)

I used marginTop and horizontal of 5 and marginBottom of 20 and put `flex: 1` to container.

![image](https://user-images.githubusercontent.com/22944576/82499017-85ef4f80-9ab6-11ea-83c8-8ff8d9ac0556.png)

**Comment by Vasault** [comment] 2020-05-20 21:48
ok i'm still unable to make this to work, here is my code for navigation

```
const HoursReportStack = createStackNavigator({
  HoursReport: {
    screen: HoursReportScreen,
    navigationOptions: {
      animationEnabled: false,
      headerShown: false,
    },
  },
  ClientProyects: {
    screen: ClientProyectsScreen,
    navigationOptions: {
      animationEnabled: true,
      //gestureEnabled: true,
      //gestureDirection: 'vertical',
      headerShown: false,
    },
  },
},
{
  mode: 'modal',
  headerMode: 'none'
});
```

on my ClientProyects screen i got a view wrapper with a style that contains a style, and yet i see a full screen

**Comment by Jmzp** [comment] 2020-05-20 21:57
@Vasault Ok, but if you want to get the result that I show you, you have to build a modal type component with the properties specified in the previous comment, and not create a new screen in the stack navigator.

You should show this modal when necessary instead of navigating to another view.

```js
<Modal
          isVisible={visible}
          animationOut="fadeOut"
          hasBackdrop={false}
          coverScreen={false}
          style={styles.modal}
        >
          <View style={
            styles.container
          } />
            ...
         </View>

</Modal>

```

**Comment by mmazzarolo** [comment] 2021-08-29 13:22
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:22 UTC
Labels: question
