### ISSUE TITLE
Red outline box around modal

### ISSUE THREAD

**Issue by johnfoneill** [react-native-modal/react-native-modal#370] opened 2019-11-05 12:10 UTC
I'm new to React Native and am not ruling out something environmental, but...  I've implemented the modal example, "A complete example" from the readme file and there is a thin red outline around the modal.  Is there something in the configuration to turn this off?  

<img width="806" alt="red_outline" src="https://user-images.githubusercontent.com/5250348/68206555-9f093680-ff92-11e9-9762-2d64e8674d59.png">

**Comment by viiirossy** [comment] 2019-11-05 15:22
try 
margin: 0

**Comment by johnfoneill** [comment] 2019-11-07 02:19
thank you.  No luck on margin: 0

This is the code referenced from the readme.

```
import React, { Component } from "react";
import { Button, Text, View } from "react-native";
import Modal from "react-native-modal";

export default class ModalTester extends Component {
  state = {
    isModalVisible: false
  };

  toggleModal = () => {
    this.setState({ isModalVisible: !this.state.isModalVisible });
  };

  render() {
    return (
      <View style={{ flex: 1 }}>
        <Button title="Show modal" onPress={this.toggleModal} />
        <Modal isVisible={this.state.isModalVisible}>
          <View style={{ flex: 1 }}>
            <Text>Hello!</Text>
            <Button title="Hide modal" onPress={this.toggleModal} />
          </View>
        </Modal>
      </View>
    );
  }
}
```

**Comment by Robmcmon** [comment] 2019-12-12 03:00
I'm having this exactly same issue. It just forces the modal to the left and puts a red outline around it for no reason.

**Comment by margaritageleta** [comment] 2020-03-14 17:53
Any solution on this issue?

**Comment by vjsingh** [comment] 2020-03-26 21:03
Having the same issue on web

**Comment by rewieer** [comment] 2020-04-02 05:37
Can you submit a reproducible repository ? 
We didn't test RNM much on web, so I can't tell about this platform.

**Comment by Federkun** [comment] 2020-04-06 11:06
Same issue. I ended up replacing RNW's modal with a simple View:

```diff
diff --git a/node_modules/react-native-modal/dist/modal.js b/node_modules/react-native-modal/dist/modal.js
index 2e3f530..341a17e 100644
--- a/node_modules/react-native-modal/dist/modal.js
+++ b/node_modules/react-native-modal/dist/modal.js
@@ -435,7 +435,7 @@ export class ReactNativeModal extends React.Component {
                 hasBackdrop && backdrop,
                 containerView));
         }
-        return (React.createElement(Modal, Object.assign({ transparent: true, animationType: 'none', visible: this.state.isVisible, onRequestClose: onBackButtonPress }, otherProps),
+        return (React.createElement(Platform.OS === 'web' ? View : Modal, Object.assign({ transparent: true, animationType: 'none', visible: this.state.isVisible, onRequestClose: onBackButtonPress }, otherProps),
             hasBackdrop && backdrop,
             avoidKeyboard && (React.createElement(KeyboardAvoidingView, { behavior: Platform.OS === 'ios' ? 'padding' : undefined, pointerEvents: "box-none", style: computedStyle.concat([{ margin: 0 }]) }, containerView)),
             !avoidKeyboard && containerView));
```

**Comment by Mehebbet13** [comment] 2020-04-11 12:57
Try:<Modal
                       style={{borderWidth:0,borderColor:'white'}}
                >
it works for me

**Comment by haveamission** [comment] 2020-04-16 12:29
@Federkun did you make a PR for this? I am also testing this on RNW and seeing the same issue

**Comment by haveamission** [comment] 2020-04-16 12:35
Actually, what should probably happen until RNW modal is released is a custom "modal". I have to implement something similar for my project so I might write a PR.

**Comment by jamesrotanson** [comment] 2020-05-04 11:06
Also seeing this issue. Submitted a question on StackOverflow and got pointed here: https://stackoverflow.com/questions/61287414/react-native-modal-core-component-always-visible-with-red-border-even-when-setti?noredirect=1#comment108870569_61287414

**Comment by Bulatbik** [comment] 2020-05-04 11:17
I ended up using modal-enhanced-react-native-web. 
https://www.npmjs.com/package/modal-enhanced-react-native-web

**Comment by kopax** [comment] 2020-07-06 10:07
I can't remove the red square in the browser. Is there a workaround?

**Comment by fibo** [comment] 2020-10-04 17:15
I found a workaround but TypeScript complains since Modal as no `style` prop, something like

```
const styles = StyleSheet.create({
container: {
  alignSelf: 'flex-start',
  backgroundColor: 'white',
  borderColor: 'gray',
  borderRadius: 4,
  borderWidth: 1,
  margin: 2
},


// then

<Modal
  ... other props
  style={isWeb && styles.container}
>
```

**Comment by coldflame426** [comment] 2020-10-23 02:41
@Bulatbik I assume this library https://www.npmjs.com/package/modal-enhanced-react-native-web doesn't support Typescript. Do you have any solution for this?

**Comment by mmazzarolo** [comment] 2021-08-29 13:27
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:27 UTC
Labels: question, missing reproducible, missing details
