### ISSUE TITLE
How to make scroll position not reset

### ISSUE THREAD

**Issue by dominicsavb** [react-native-modal/react-native-modal#501] opened 2020-12-19 17:21 UTC
When I have a modal with scrollview as children... And I change scroll position... when i reopen that modal, scroll position is reset to top position. how to make scroll position back as i last scroll...

Thank you

**Comment by owaiskhan3** [comment] 2020-12-24 06:00
I am also in search for the answer of this query. Any suggestion would be highly appreciated.

**Comment by NathanBeesley** [comment] 2021-05-21 12:57
Technically if you hid the modal it was taken off the stack. You would need to store the current scroll position outside of the Modal component and pass it back in upon re-render.

**Comment by mmazzarolo** [comment] 2021-08-29 13:10
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:10 UTC
Labels: question
