### ISSUE TITLE
How to enable onSwipeComplete and onBackdropPress propert at the same time?

### ISSUE THREAD

**Issue by berksafran** [react-native-modal/react-native-modal#283] opened 2019-04-03 17:05 UTC
Hello,

I have a problem like i write in title. My modal code is running when **onSwipeComplete** property is active. But it didn't run with **onBackdropPress**. I added `<TouchableWithoutFeedback>` instead of first `<View>`. At this time, onSwipeComplete property is not running correctly. 

How can i run both of them at the same time? 

You can my code as below which is running correctly with `onSwipeComplete`:

```
`<View> 
          <Modal
            isVisible={visible}
            onBackdropPress={() => alert("ok.")}
            onSwipeComplete={() => this.onVisibleModal(false)}
            swipeDirection="down"
            style={{
              flex: 1,
              width: "100%",
              justifyContent: "flex-end",
              margin: 0
            }}
          >
            {this.renderModal()}
          </Modal>
        </View>
        </View>`
```

and renderModal() code:

````
renderModal = () => {
    const { source, pressedPhoto } = this.state;
    return (
      <View
        style={{
          flex: 1,
          justifyContent: "flex-end"
        }}
      >
        <View style={styles.containerModal}>
          <View style={{}}>
            <Text style={styles.modalTitle}>Grup Fotoğrafı Seç {height} </Text>
          </View>
          <View style={styles.containerScroll}>
            <Image
              style={{ width: 320, height: 320 }}
              source={{uri: source}}
            />
            <View />
          </View>

          <View style={styles.containerButton}>
            <TouchableOpacity
              activeOpacity={0.5}
              style={styles.buttonClose}
              onPress={() => this.onVisibleModal(false)}
            >
              <Icon
                name="x"
                size={styles.icon.fontSize}
                color="#47525E"
              />
            </TouchableOpacity>
            <TouchableOpacity activeOpacity={0.5} 
            style={styles.buttonSave}
            onPress={() => {
              this.onVisibleModal(false);
              this.onSelectGroupProfilePicture(pressedPhoto);
            }}>
              <Text style={styles.buttonText}>Seç</Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    );
  };
````

**Comment by berksafran** [comment] 2019-04-05 19:17
Anyone help ?

**Comment by mmazzarolo** [comment] 2021-08-29 13:20
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:20 UTC
Labels: question
