### ISSUE TITLE
Accessibility resets to the first element on close.

### ISSUE THREAD

**Issue by guilhermehj** [react-native-modal/react-native-modal#456] opened 2020-07-07 14:35 UTC
## Ask your Question

Hey!

I'm working in an app with accessibility, and I'm having a problem when I close the modal. When opening the modal the focus of accessibility is working, but when closing the modal, accessibility resets to the first element of the screen, does anyone have any solution for this?

I tried to use `AccessibilityInfo.setAccessibilityFocus` but is not working for me, i don't know why. Using this code the first element is focused twice, like the element doesn't exists.

```
const containerRef = useRef(null);
...

const onModalClose = useCallback(() => {
    if (reactTag) {
      if (Platform.OS === 'ios') {
        AccessibilityInfo.setAccessibilityFocus(reactTag);
      } else if (Platform.OS === 'android') {
        UIManager.sendAccessibilityEvent(
          reactTag,
          UIManager.AccessibilityEventTypes.typeViewFocused
        );
      }
    }
  }, [reactTag]);

...

useEffect(() => {
    if (containerRef) {
      const reactTag = findNodeHandle(containerRef.current);
      setReactTag(reactTag);
    }
  }, [containerRef]);
```

**Comment by mmazzarolo** [comment] 2021-08-29 13:15
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:15 UTC
Labels: question

**Comment by nethergrim** [comment] 2022-03-11 10:58
I'm currently having the same issue with 13.0.1.
Once modal is closed, accessibility focus is reset to the first element, instead of keeping it on latest focused element.

**Comment by nethergrim** [comment] 2022-03-14 19:07
Actually after some testing I figured out that it's a problem in an underlying
`import { Modal } from 'react-native';`

We should definitely try to overcome that

**Comment by chris-rodgers** [comment] 2022-04-25 07:48
I am also experiencing this issue
