### ISSUE TITLE
Modal height

### ISSUE THREAD

**Issue by Talha-Jawed** [react-native-modal/react-native-modal#518] opened 2021-01-30 08:14 UTC
i implement modal height in style props but height does'nt apply .. show the full screen height modal still

**Comment by mmazzarolo** [comment] 2021-08-29 13:09
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:09 UTC
Labels: question

**Comment by kutsan** [comment] 2021-08-29 13:15
You could probably easily convert this issue into a discussion and maybe give an answer there.

**Comment by dqii** [comment] 2021-11-29 18:31
https://github.com/react-native-modal/react-native-modal/discussions/628
