### ISSUE TITLE
navigation bar  issue ..

### ISSUE THREAD

**Issue by sooraj-panchal** [react-native-modal/react-native-modal#493] opened 2020-12-04 07:47 UTC
## Ask your Question
r
react-native modals backdrop opacity or color does not affect on navigation bar color and status bar color,
 need exact like react-native Alert dialog that's backdrop opacity cover navigation bar and status bar but modal cannot..
how to achieve this.. 
  thanks in advance..

**Comment by LimanASL** [comment] 2021-01-07 04:10
Same here

**Comment by SarvaDev-123** [comment] 2021-05-23 14:06
Same here

**Comment by F3WS** [comment] 2021-06-09 13:54
I had the same issue, solved it by using initialWindowMetrics from react-native-safe-area-context to get the device height and adding statusBarTranslucent to the modal

`import React from 'react'
import Modal from 'react-native-modal'
import { Platform, Dimensions } from 'react-native'
import { initialWindowMetrics } from 'react-native-safe-area-context'

const MyModal = ({ children, isVisible }) => {
  const { frame } = initialWindowMetrics
  const deviceWidth = Dimensions.get('window').width
  const deviceHeight = Platform.OS === 'ios' ? Dimensions.get('window').height : frame.height
  return (
    <Modal isVisible={isVisible} statusBarTranslucent deviceWidth={deviceWidth} deviceHeight={deviceHeight}>
      {children}
    </Modal>
  )
}

export default MyModal`

**Comment by F3WS** [comment] 2021-06-09 14:04
I had the same issue, solved it by using initialWindowMetrics from react-native-safe-area-context to get the device height and adding statusBarTranslucent to the modal

```javascript
import React from 'react'
import Modal from 'react-native-modal'
import { Platform, Dimensions } from 'react-native'
import { initialWindowMetrics } from 'react-native-safe-area-context'

const MyModal = ({ children, isVisible }) => {
  const { frame } = initialWindowMetrics
  const deviceWidth = Dimensions.get('window').width
  const deviceHeight = Platform.OS === 'ios' ? Dimensions.get('window').height : frame.height
  return (
    <Modal isVisible={isVisible} statusBarTranslucent deviceWidth={deviceWidth} deviceHeight={deviceHeight}>
      {children}
    </Modal>
  )
}

export default MyModal
```

**Comment by mmazzarolo** [comment] 2021-08-29 13:28
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:28 UTC
Labels: question
