### ISSUE TITLE
not close when clicking mouse.

### ISSUE THREAD

**Issue by dsagredo** [react-native-modal/react-native-modal#441] opened 2020-06-02 23:35 UTC
## Ask your Question

Hello, I want to know, 
How the modal will not close when clicking outside it. Click the button below to try it?

**Comment by mmazzarolo** [comment] 2021-08-29 13:21
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:21 UTC
Labels: question
