### ISSUE TITLE
Issue with scroll and swipe

### ISSUE THREAD

**Issue by atifaziz1** [react-native-modal/react-native-modal#521] opened 2021-02-10 10:12 UTC
I am using react-native modal, `v11.4.0`. 

react-native: 0.63.3.
Platform: Ios and Android.

I am facing issue two issues.

For IOS and Android:
1. if offset is greater than 0, modal swipe down didn't work.

Only for Android:
1. offset is not persist, when i release scroll and try to again scroll, offset turn to zero again. 
Inside Modal, i have scrollview.

Hope you understand my issue and will help me.

**Comment by mmazzarolo** [comment] 2021-08-29 13:09
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:09 UTC

**Comment by Nestor231** [comment] 2022-05-10 02:33
hi @mmazzarolo , im having similar issues on my end as well. I have a modal that i have enabled swipeDirection down behavior, which has a child scrollview in it. 

If I don't enable the swipe function in the modal, the scrollview works, but if swipe function in modal is enabled, 
scrollview does not work

**Comment by RuzenDev** [comment] 2022-09-30 07:08
AM having the same issue...

Swipe works = Scroll Not Working 

Scroll works = Swipe Not Working

**Comment by JimTeva** [comment] 2024-01-24 07:19
@atifaziz1 , @Nestor231 , @RuzenDev Ok I just noticed this awesome prop: propagateSwipe, set it to true and you will be happy haha

**Comment by MussadiqAli** [comment] 2024-05-23 08:01
1. Pass **_propagateSwipe_** prop to **ReactNativeModal**
2. Use <Pressable></Pressable> inside Scrollview,  
3. Add your scrollable content inside Pressable, so Scoll will work fine.
4. you can swipe outside of Scrollview area. 

example:
`<ReactNativeModal
      backdropColor="rgba(50, 62, 72, 0.6)"
      backdropOpacity={1}
      statusBarTranslucent
      swipeDirection={'down'}
      propagateSwipe
      onSwipeComplete={() => setShow(false)}
      useNativeDriver={true}
      isVisible={show}>
      <View >
        <View>
             {/*   Swipe will work here  */}
        </View>
        <ScrollView>
          <Pressable>
             {/* Place Scrollable Content here */}
          </Pressable>
        </ScrollView>
      </View>
    </ReactNativeModal>
`

**Comment by edsonjuniornarvaes** [comment] 2025-03-21 15:25
Thank you, it worked perfectly
