### ISSUE TITLE
avoiding keyboard when coverScreen is false

### ISSUE THREAD

**Issue by Bayramito** [react-native-modal/react-native-modal#524] opened 2021-03-06 00:17 UTC
How can I avoid the keyboard when I set the `coverScreen` to `false`?

I need to set the `coverScreen` prop to `false` becouse i am displaying a popup alert modal when my  modal is alredy open.

**Comment by pratius** [comment] 2021-03-10 07:03
I have handled like this.

` <Modal isVisible={this.state. isModalVisible}
            **coverScreen={this.state. isModalVisible}**>
</Modal>`

**Comment by mmazzarolo** [comment] 2021-08-29 13:12
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:12 UTC
Labels: question
