### ISSUE TITLE
Is it possible to show certain height at init, then show it full on user swipe up?

### ISSUE THREAD

**Issue by jeafgilbert** [react-native-modal/react-native-modal#514] opened 2021-01-15 04:29 UTC
Is it possible to show certain height at init, maybe 1/3 or defined init height, then show 100% height on modal swipe up?

**Comment by mmazzarolo** [comment] 2021-08-29 13:10
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:10 UTC
Labels: question
