### ISSUE TITLE
Not clear how to use scrollOffsetMax

### ISSUE THREAD

**Issue by ValentinH** [react-native-modal/react-native-modal#423] opened 2020-04-13 21:40 UTC
First, thank you really much for this nice component.

After looking at the Readme, the examples and the issues mentioning it, I'm still not sure to understand what `scrollOffsetMax` exactly does and what value I should set.

I'm trying to implement a modal with a scrollable content + drag-down to dismiss feature: it's working pretty well except for one thing.

When my scrollview is scrolled at the top and I tried to scroll to the bottom of it, it feels like there is an "invisible force" always bringing to scroll view to the top. If I scroll a lot, then this force stops and I manage to properly scroll within my view.

When I place a few logs, I've noticed that the "weird" behavior is always happening when the `scrollTo` callback is called. After a while, it's not called anymore and everything goes smoothly.

Here's my implementation:
```tsx
const MyModal: React.FC<Props> = ({ isOpen, onClose }) => {
  const { data } = useData()

  const [scrollOffset, setScrollOffset] = React.useState(0)
  const scrollViewRef = React.useRef<ScrollView | null>(null)

  const handleOnScroll = (event: NativeSyntheticEvent<NativeScrollEvent>) => {
    setScrollOffset(event.nativeEvent.contentOffset.y)
  }

  const handleScrollTo = (p: any) => {
    if (p.y > 0) {
      scrollViewRef.current?.scrollTo(p)
    }
  }

  return (
    <Modal
      isVisible={isOpen}
      onBackButtonPress={onClose}
      onSwipeComplete={onClose}
      swipeDirection={['down']}
      propagateSwipe
      scrollTo={handleScrollTo}
      scrollOffset={scrollOffset}
    >
      <View style={styles.root}>
        <ScrollView ref={scrollViewRef} onScroll={handleOnScroll} scrollEventThrottle={16}>
          {data && (
            <HTML
              html={data}
              baseFontStyle={{
                fontSize: 16,
              }}
              classesStyles={{
                underline: { textDecorationLine: 'underline' },
              }}
            />
          )}
        </ScrollView>
      </View>
    </Modal>
  )
}
```

This is on Android, I need to check on iOS.

**Comment by roni-castro** [comment] 2020-04-15 01:27
I do not understand it either. The same issue is happening with me on Android. If I add `scrollOffsetMax={500}` (max-length of my view) it happens less frequently compared to `scrollOffsetMax={0}`

**Comment by ValentinH** [comment] 2020-04-15 05:02
In my component I tried many values like 0, 0.0001, -100, 100, -deviceHeight, deviceHeight or 1000000. 🙈

**Comment by ValentinH** [comment] 2020-04-15 22:07
I played a bit with the code of the `Modal` component and I've noticed that the laggy scroll was happening when the scroll was handled by the Modal when calling the `scrollTo` prop: https://github.com/react-native-community/react-native-modal/blob/master/src/modal.tsx#L389-L394

I need to dig deeper to check if there is a way to get a smoother scroll when controlling via the Modal.

I've also checked in `production` mode and there is the same issue.

**Comment by papigers** [comment] 2020-04-19 17:58
As far as I understand it the `maxScrollOffset` value should be the difference between the height of the scroll view content and, the height of the scroll view wrapper (not necessary parent, but the element that limits the height of the scroll view).
This can be easily calculated here:
```js
  const onScroll = React.useCallback((e) => {
    setScrollOfsset(e.nativeEvent.contentOffset.y);
    setMaxScrollOfsset(
      e.nativeEvent.contentSize.height - e.nativeEvent.layoutMeasurement.height,
    );
  }, []);
```

That being said, I'm still not getting the wanted result. It seemed that sometimes the scroll view content loses focus and swiping just causes the modal to swipe.

**Comment by ValentinH** [comment] 2020-04-19 18:04
I noticed that the biggest part of the lag feeling was because the ScrollView content was rerendered while scrolling. As it was a quite long webview, it was slow. I wrapped my HTML component with `React.memo` and it's much better.

However, I removed to swipe gesture because the initial scroll was still feeling bad.

**Comment by papigers** [comment] 2020-04-19 18:25
I've found out that the problem (for me, at least), was that I also set `up` as a `swipeDirection` for some reason it breaks the scroll view. For now, I'm settling on just using `swipeDirection={['down']}`.

**Comment by dharshatharan** [comment] 2021-01-10 07:21
The following code seemed to give me smooth scrolling. I added a TouchableOpacity component inside the scroll view.

```
  handleOnScroll = (event: any) => {
    this.setState({
      scrollOffset: event.nativeEvent.contentSize.height - event.nativeEvent.layoutMeasurement.height,
    });
  };

```
```
            <ScrollView
              ref={this.scrollViewRef}
              onScroll={this.handleOnScroll}
              scrollEventThrottle={16}>
              <TouchableOpacity activeOpacity={1}>
                <View style={styles.scrollableModalContent1}>
                  <Text style={styles.scrollableModalText1}>
                    You can scroll me up! 👆
                  </Text>
                </View>
                <View style={styles.scrollableModalContent2}>
                  <Text style={styles.scrollableModalText2}>
                    Same here as well! ☝
                  </Text>
                </View>
              </TouchableOpacity>
            </ScrollView>
```

**Comment by mmazzarolo** [comment] 2021-08-29 13:24
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:24 UTC
Labels: question
