### ISSUE TITLE
Does this work with React Native Web?

### ISSUE THREAD

**Issue by haveamission** [react-native-modal/react-native-modal#424] opened 2020-04-16 12:26 UTC
Does this work with React Native Web? If so, are there any other configuration steps I need to do?

I am testing it, and my RNW site doesn't crash or anything, but I am noticing that it just displays all the content at once without hiding it.

Both of these items surrounded by red boxes should be inside modals

![image](https://user-images.githubusercontent.com/10475533/79456098-e5d86f00-7fbb-11ea-8060-b2fc9610a4ca.png)

Does this library just not support RNW? What is the best way to resolve this problem?

**Comment by haveamission** [comment] 2020-04-16 13:59
It does not, switched to this library that does:

https://www.npmjs.com/package/modal-react-native-web

**Comment by kopax** [comment] 2020-05-27 08:58
Is there any plan to support the web ?

**Comment by virgil9306** [comment] 2020-08-20 07:48
@kopax : See https://github.com/necolas/react-native-web/pull/1646

I hope that will be usable soon for react-native-web. Until then I will combine this and the repo @haveamission mentioned.

**Comment by mmazzarolo** [comment] 2021-08-29 13:24
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:24 UTC
Labels: question
