### ISSUE TITLE
Trigger Function for Animation

### ISSUE THREAD

**Issue by grumpyTofu** [react-native-modal/react-native-modal#492] opened 2020-12-02 01:56 UTC
Is there a way to trigger animation based on a function? For example, could the modal 'wobble' when a user enters an incorrect value?

**Comment by mmazzarolo** [comment] 2021-08-29 13:11
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:11 UTC
Labels: question
