### ISSUE TITLE
set backdropOpacity on Modal.BottomModal

### ISSUE THREAD

**Issue by iman2420** [react-native-modal/react-native-modal#498] opened 2020-12-12 13:13 UTC
How to set `backdropOpacity `on `Modal.BottomModal`

              `<Modal.BottomModal
                onBackdropPress={()=>{setModalVisible(false)}}
                backdropOpacity={0}
                backdropColor="transparent"
                style={{marginEnd : 100 , marginStart: 100}}
                visible={modalIsVisible}
                swipeDirection={['down']} // can be string or an array
                swipeThreshold={100} // default 100
                onSwipeOut={(event) => {
                    setModalVisible(false)
                }}
            >
                <ModalContent style={{paddingTop: 10}}>
                    <ModalAgent onClose={() => setModalVisible(false)}/>
                </ModalContent>
            </Modal.BottomModal>`

**Comment by mmazzarolo** [comment] 2021-08-29 13:10
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:10 UTC
Labels: question
