### ISSUE TITLE
The View under the Navbar

### ISSUE THREAD

**Issue by mingxin-yang** [react-native-modal/react-native-modal#425] opened 2020-04-17 09:42 UTC
## Ask your Question
```
<Modal
    backdropColor={'black'}
    backdropOpacity={0.7}
    deviceHeight={actions.getHeight()}
    coverScreen={false}
    hasBackdrop={false}
    deviceHeight={width}
    animationIn={'slideInDown'}
    animationInTiming={500}
    animationOut={'slideOutUp'}
    animationOutTiming={500}
    swipeDirection="up"
    useNativeDriver
    swipeThreshold={20}
    onSwipeComplete={() => {
    console.log("onSwipeComplete")
    this.props.onBackdropPress()
    }}
    style={{flex:1,flexDirection: 'column', justifyContent: 'flex-start', margin: 5, marginTop:-Header.HEIGHT}}
    {...this.props}
>
```
When I use **coverScreen={false}** and **hasBackdrop={false}** and set **marginTop:-Header.HEIGHT** , the view will under the Navbar

**Comment by mmazzarolo** [comment] 2021-08-29 13:23
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:23 UTC
Labels: question
