### ISSUE TITLE
Platform native-like animations

### ISSUE THREAD

**Issue by Dem0n13** [react-native-modal/react-native-modal#540] opened 2021-04-12 11:50 UTC
As I see `slideInUp` is used as `animationIn` default and `slideOutDown` used as `animationOut` default.
What animations can I use to simulate native behavior for android and ios platforms?

**Comment by mmazzarolo** [comment] 2021-08-29 13:06
Hi! 
I'm closing this issue because it's a question and not a bug report.    
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:06 UTC
Labels: question
