### ISSUE TITLE
Modal-to-Modal transition

### ISSUE THREAD

**Issue by CyberMew** [react-native-modal/react-native-modal#481] opened 2020-09-22 17:40 UTC
## Ask your Question

1st modal (in a FirstFunctionComponent) triggers 2nd modal (in a SecondFunctionComponent) to load via some redux state (say something like, setting both `show1stModal` to `false` and `show2ndModal` to `true`) inside FirstFunctionComponent's `onModalHide` prop. All is fine and expected here. Happy flow 😃 

However, the 1st modal _also_ has a button, that triggered a series of event that causes both components to be unmounted, and then remounted. This means 1 thing: `onModalHide` is skipped. BUT redux state is set here too (i.e. both `show1stModal` to `false` and `show2ndModal` to `true`).

When both components have been remounted, 1st modal does not show as expected. HOWEVER, 2nd modal ALSO does not show, despite the state saying that it should show.

What I want to know is, even though 1st Modal has been destroyed and no longer (`visible` false) shows on remount, why can't 2nd Modal show up? Is this a bug or 'intended' behaviour? What am I missing with regards to this unmount/remount behaviour?

**Comment by alimtunc** [comment] 2020-09-24 14:03
I've got the same issue, `onModalHide` is never triggered.. even when I log directly into the library.

**Comment by mmazzarolo** [comment] 2021-08-29 13:12
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Closed by mmazzarolo** 2021-08-29 13:12 UTC
Labels: question

**Comment by CyberMew** [comment] 2021-08-30 00:34
No problem. It has been resolved in #484 and I forgot to close this. To answer my own question, this is intended behaviour.
